apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: kevmeans/metronome-node-app:2
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "backenduser"
            - name: DB_PASSWORD
              value: "backenduserpassword123"
            - name: DB_DATABASE
              value: "metronome"
          ports:
            - containerPort: 3080
