apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 3080
  type: LoadBalancer
